<a href="https://colab.research.google.com/github/keshavchandel13/numpy/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [ ]:
import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


# Array

In [ ]:
# creating a array
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


# Create user defined array


In [ ]:
#creating user defined array
import numpy as np
lst = [] # taking empty list
b = int(input("enter the number of digits you want to enter in array: "))
for i in range(0,b):
  inp = int(input("Enter value "))
  lst.append(inp)
arr = np.array(lst)
print(arr)
print(type(arr))

enter the number of digits you want to enter in array: 3
Enter value 10
Enter value 20
Enter value 30
[10 20 30]
<class 'numpy.ndarray'>


### Types of arrays


1.   1-D arrays [1 2 3 4]
2.   2-D arrays [[1 2 3 4]]
3.   3-D arrays [[[1 2 3 4 ]]]
4.   Higher Dimension Arrays
--> ndim is the function used to determine the dimension of array

  



In [ ]:
# two dimension array
import numpy as np
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print("two dimension array is: \n",arr2)
print(arr2.ndim)
# three dimension array
arr3 = np.array([[[1,2,3,4],[5,6,7,8],[7,8,9,10]]])
print("three dimension array is : \n",arr3)
print(arr3.ndim)

# 10-D array
arr10 = np.array([1,2,3,4],ndmin=10)
print("10-D array: \n",arr10)
print(arr10.ndim)

two dimension array is: 
 [[1 2 3 4]
 [1 2 3 4]]
2
three dimension array is : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 7  8  9 10]]]
3
10-D array: 
 [[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [ ]:
# zero array
import numpy as np
print("Zero array: ")
arr_zero = np.zeros(4)
print(arr_zero) # 1-D
arr_zero1 = np.zeros((2,3))
print()
print(arr_zero1) #2-D
print()

# One's array
print("one's array: ")
arr_one = np.ones(4)
print(arr_one) # 1-D
print()
arr_one1 = np.ones((2,8))
print(arr_one1) # 2-D
print()

# Empty Array
print("Empty array: ")
ar_emp = np.empty(4)
print(ar_emp)
print()

# Range Array
print("Range array: ")
ar_rn = np.arange(9)
print(ar_rn)
print()

# Diagonal Array
print("Diagonal array: ")
ar_dg = np.eye(3)
print(ar_dg)
print()

# Special Interval array (linespace)
print("Special Interval array: ")
ar_sp = np.linspace(0,20,num=5)
print(ar_sp)





Zero array: 
[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

one's array: 
[1. 1. 1. 1.]

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

Empty array: 
[1. 1. 1. 1.]

Range array: 
[0 1 2 3 4 5 6 7 8]

Diagonal array: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Special Interval array: 
[ 0.  5. 10. 15. 20.]


# Random

In [ ]:
import numpy as np
# Rand(): Generate Number between 0 & 1
var = np.random.rand(4)
print("Array using rand(): \n",var)
print()
var1 = np.random.rand(2,5)
print("Array using rand() 2-D:\n",var1)
print()

# randn(): Generate Number close to zero, +ve or -ve as well
var2 = np.random.randn(5)
print("Array using randn(): 1-D:\n",var2)
print()
var3 = np.random.randn(2,3)
print("array using randn 2-D: \n",var3)
print()

# ranf(): Random sampling in numpy, Returns array of specified shape and fills it with random float between [0.0, 1.0)
var4 = np.random.ranf(4)
print("Array using ranf() 1-D:\n",var4)
print()

# randint(): generate the random number between a range
# var5 = np.random.randint(min,max,size)
var5 = np.random.randint(5,20,5)
print("Array using randint(): 1-D:\n",var5)
print()



Array using rand(): 
 [0.87747728 0.0972548  0.83650654 0.91131523]

Array using rand() 2-D:
 [[0.02000192 0.68750281 0.86745746 0.1725827  0.7112917 ]
 [0.19896727 0.87206652 0.95439167 0.30033965 0.37692319]]

Array using randn(): 1-D:
 [ 0.8174317   0.11542216  0.01577104 -0.66518159  0.44058919]

array using randn 2-D: 
 [[ 0.16484025 -0.08596793 -1.44890043]
 [ 1.41835974  1.37429785 -1.47793834]]

Array using ranf() 1-D:
 [0.88327713 0.70695148 0.67766419 0.82313051]

Array using randint(): 1-D:
 [11 11  5  8 12]



# DATATYPE IN NUMPY ARRAY'S


In [ ]:
import numpy as np
# Finding datatype using .dtype
var = np.array([1,2,3,4])
print("Data type: ",var.dtype)
print()
var = np.array(["a","b","c"])
print("Data Type: ",var.dtype)

# Changing the datatype
x = np.array([1,2,3,4],dtype=np.float16)
print(x.dtype)
x = np.array([1,2,3,4],dtype= "i")
print(x.dtype)

# changing datatype using astype
y = np.array([1,2,3])
new = y.astype(float)
print(new.dtype)


Data type:  int64

Data Type:  <U1
float16
int32
float64


# Arithmetic operation on array

In [ ]:
import numpy as np
# addition
var = np.array([1,2,3,4])
varadd = var + 3
print("The addtion of the array is: ",varadd)
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,9,10,9])
arrsum = arr1 + arr2
print("The addition of two array is: ",arrsum)

# subraction
varsub = var - 3
print("The subraction of the array is: ",varsub)

# division
vardiv = var / 3
print("The division of the array is: ",vardiv)

# multiplication
varmul = var * 3
print("The multiplication of the array is: ",varmul)



The addtion of the array is:  [4 5 6 7]
The addition of two array is:  [ 3 11 13 13]
The subraction of the array is:  [-2 -1  0  1]
The division of the array is:  [0.33333333 0.66666667 1.         1.33333333]
The multiplication of the array is:  [ 3  6  9 12]


# Arithamatic Functions

In [ ]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8])
# Min of array
print("Minimum: ",np.min(var))
# Max of array
print("Max: ",np.max(var))
# Position of min element in array
print("Position min: ",np.argmin(var))
# Position of max element in array
print("Position max: ",np.argmax(var))
# Square root of array
print("Square root: ",np.sqrt(var))
# Sin of array
print("Sin: ",np.sin(var))
# cumulative sum
print("Cumulative sum: ",np.cumsum(var))

Minimum:  1
Max:  8
Position min:  0
Position max:  7
Square root:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712]
Sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825]
Cumulative sum:  [ 1  3  6 10 15 21 28 36]


# Shape & Re- shape
converting 1-D array to 2-D
or 2-D array to 3-D array
or n-D array to n-D array

In [ ]:
import numpy as np
var = np.array([[1,2,3],[2,5,6]])
print(var)
print(var.shape)
print()

# multi-D array
var1 = np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)
print(var1.shape)

[[1 2 3]
 [2 5 6]]
(2, 3)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


Reshape


In [ ]:
var = np.array([1,2,3,4,5,6])
print(var.shape)
# 1-D to 2-D
x = var.reshape(2,3)
print(x)
print(x.ndim)
# 2-D to 1-D
x1 = x.reshape(-1)
print(x1)
print(x1.ndim)


(6,)
[[1 2 3]
 [4 5 6]]
2
[1 2 3 4 5 6]
1


# BroadCasting

In [ ]:
import numpy as np
var1 = np.array([1,2,3])
var2 = np.array([1,2])
# print(var1 + var2) # throws error

var3 = np.array([1,2,3])
var4 = np.array([[1],[2],[3]])
print(var3)
print(var4)
print( var3 + var4)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing & Slicing

In [ ]:
# Indexing: The indexing is both +ve & -ve similar to list
import numpy as np
var = np.array([9,8,6])
print(var[2])
print(var[-1])
print()
# 2-D array
var2 = np.array([[9,8,7],[4,5,6]])
print(var2[0,2])
print()
# 3-D array
var3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[2,4,5]]])
print(var3)
print(var3[0,1,2])


6
6

7

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [2 4 5]]]
6


In [ ]:
# slicing
var = np.array([33,22,77,33,12,56,44])
print(var[1:4])
print(var[1:])

# 2-D
var2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(var2[0,1:4])

[22 77 33]
[22 77 33 12 56 44]
[2 3 4]


# Iteration

In [ ]:
# Iteration
import numpy as np
var = np.array([9,8,7,6,5,4,3])
for i in var:
  print(i,end="  ")
print()
print()
# 2-D
var2 = np.array([[1,2,3,4],[5,6,7,8]])
print()
for j in var2:
  # print(j)
  for k in j:
    print(k,end="  ")

# iterate without using multiple  loop
print()
for x in np.nditer(var2):
  print(x,end="  ")


9  8  7  6  5  4  3  


1  2  3  4  5  6  7  8  
1  2  3  4  5  6  7  8  

In [ ]:
# indexing
for x,d in np.ndenumerate(var2):
  print(x,d)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Copy vs View

In [ ]:
import numpy as np
# copy
var = np.array([1,2,3,4])
co = var.copy()

print("var: ",var)
print("copy: ",co)

# view: Changes madeb in original array will make in view also
var1 = np.array([1,2,3,4])
vi = var1.view()

print("var1: ",var1)
print("view: ",vi)

var:  [1 2 3 4]
copy:  [1 2 3 4]
var1:  [1 2 3 4]
view:  [1 2 3 4]


# Join AND Split ARRAY

In [7]:
import numpy as np
var = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
arr = np.concatenate((var,var2))
print(arr)
# 2-D array
var3 = np.array([[1,2],[3,4]])
var4 = np.array([[5,6],[7,8]])
arr2 = np.concatenate((var3,var4),axis=1)
print(arr2)

[1 2 3 4 5 6 7 8]
[[1 2 5 6]
 [3 4 7 8]]
