<a href="https://colab.research.google.com/github/keshavchandel13/numpy/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


# New Section

In [ ]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [6]:
# testing which is fast array or list

# List
print("Time for List")
%timeit [j**4 for j in range(1,9)]

#array
import numpy as np
print("Time for array")
%timeit np.arange(1,9)**4 #arrange function creates the array

Time for List
3.95 µs ± 361 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Time for array
2.48 µs ± 63.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Array

In [7]:
# creating a array
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


# Create user defined array


In [12]:
#creating user defined array
import numpy as np
lst = [] # taking empty list
b = int(input("enter the number of digits you want to enter in array: "))
for i in range(0,b):
  inp = int(input("Enter value "))
  lst.append(inp)
arr = np.array(lst)
print(arr)
print(type(arr))

enter the number of digits you want to enter in array: 3
Enter value 10
Enter value 20
Enter value 30
[10 20 30]
<class 'numpy.ndarray'>
