<a href="https://colab.research.google.com/github/keshavchandel13/numpy/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [ ]:
import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


# Array

In [ ]:
# creating a array
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


# Create user defined array


In [ ]:
#creating user defined array
import numpy as np
lst = [] # taking empty list
b = int(input("enter the number of digits you want to enter in array: "))
for i in range(0,b):
  inp = int(input("Enter value "))
  lst.append(inp)
arr = np.array(lst)
print(arr)
print(type(arr))

enter the number of digits you want to enter in array: 3
Enter value 10
Enter value 20
Enter value 30
[10 20 30]
<class 'numpy.ndarray'>


### Types of arrays


1.   1-D arrays [1 2 3 4]
2.   2-D arrays [[1 2 3 4]]
3.   3-D arrays [[[1 2 3 4 ]]]
4.   Higher Dimension Arrays
--> ndim is the function used to determine the dimension of array

  



In [ ]:
# two dimension array
import numpy as np
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print("two dimension array is: \n",arr2)
print(arr2.ndim)
# three dimension array
arr3 = np.array([[[1,2,3,4],[5,6,7,8],[7,8,9,10]]])
print("three dimension array is : \n",arr3)
print(arr3.ndim)

# 10-D array
arr10 = np.array([1,2,3,4],ndmin=10)
print("10-D array: \n",arr10)
print(arr10.ndim)

two dimension array is: 
 [[1 2 3 4]
 [1 2 3 4]]
2
three dimension array is : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 7  8  9 10]]]
3
10-D array: 
 [[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [ ]:
# zero array
import numpy as np
print("Zero array: ")
arr_zero = np.zeros(4)
print(arr_zero) # 1-D
arr_zero1 = np.zeros((2,3))
print()
print(arr_zero1) #2-D
print()

# One's array
print("one's array: ")
arr_one = np.ones(4)
print(arr_one) # 1-D
print()
arr_one1 = np.ones((2,8))
print(arr_one1) # 2-D
print()

# Empty Array
print("Empty array: ")
ar_emp = np.empty(4)
print(ar_emp)
print()

# Range Array
print("Range array: ")
ar_rn = np.arange(9)
print(ar_rn)
print()

# Diagonal Array
print("Diagonal array: ")
ar_dg = np.eye(3)
print(ar_dg)
print()

# Special Interval array (linespace)
print("Special Interval array: ")
ar_sp = np.linspace(0,20,num=5)
print(ar_sp)





Zero array: 
[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

one's array: 
[1. 1. 1. 1.]

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

Empty array: 
[1. 1. 1. 1.]

Range array: 
[0 1 2 3 4 5 6 7 8]

Diagonal array: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Special Interval array: 
[ 0.  5. 10. 15. 20.]


# Random

In [ ]:
import numpy as np
# Rand(): Generate Number between 0 & 1
var = np.random.rand(4)
print("Array using rand(): \n",var)
print()
var1 = np.random.rand(2,5)
print("Array using rand() 2-D:\n",var1)
print()

# randn(): Generate Number close to zero, +ve or -ve as well
var2 = np.random.randn(5)
print("Array using randn(): 1-D:\n",var2)
print()
var3 = np.random.randn(2,3)
print("array using randn 2-D: \n",var3)
print()

# ranf(): Random sampling in numpy, Returns array of specified shape and fills it with random float between [0.0, 1.0)
var4 = np.random.ranf(4)
print("Array using ranf() 1-D:\n",var4)
print()

# randint(): generate the random number between a range
# var5 = np.random.randint(min,max,size)
var5 = np.random.randint(5,20,5)
print("Array using randint(): 1-D:\n",var5)
print()



Array using rand(): 
 [0.87747728 0.0972548  0.83650654 0.91131523]

Array using rand() 2-D:
 [[0.02000192 0.68750281 0.86745746 0.1725827  0.7112917 ]
 [0.19896727 0.87206652 0.95439167 0.30033965 0.37692319]]

Array using randn(): 1-D:
 [ 0.8174317   0.11542216  0.01577104 -0.66518159  0.44058919]

array using randn 2-D: 
 [[ 0.16484025 -0.08596793 -1.44890043]
 [ 1.41835974  1.37429785 -1.47793834]]

Array using ranf() 1-D:
 [0.88327713 0.70695148 0.67766419 0.82313051]

Array using randint(): 1-D:
 [11 11  5  8 12]



# DATATYPE IN NUMPY ARRAY'S


In [6]:
import numpy as np
# Finding datatype using .dtype
var = np.array([1,2,3,4])
print("Data type: ",var.dtype)
print()
var = np.array(["a","b","c"])
print("Data Type: ",var.dtype)

# Changing the datatype
x = np.array([1,2,3,4],dtype=np.float16)
print(x.dtype)
x = np.array([1,2,3,4],dtype= "i")
print(x.dtype)

# changing datatype using astype
y = np.array([1,2,3])
new = y.astype(float)
print(new.dtype)


Data type:  int64

Data Type:  <U1
float16
int32
float64
