<a href="https://colab.research.google.com/github/keshavchandel13/numpy/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


# Array

In [ ]:
# creating a array
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


# Create user defined array


In [ ]:
#creating user defined array
import numpy as np
lst = [] # taking empty list
b = int(input("enter the number of digits you want to enter in array: "))
for i in range(0,b):
  inp = int(input("Enter value "))
  lst.append(inp)
arr = np.array(lst)
print(arr)
print(type(arr))

enter the number of digits you want to enter in array: 3
Enter value 10
Enter value 20
Enter value 30
[10 20 30]
<class 'numpy.ndarray'>


### Types of arrays


1.   1-D arrays [1 2 3 4]
2.   2-D arrays [[1 2 3 4]]
3.   3-D arrays [[[1 2 3 4 ]]]
4.   Higher Dimension Arrays
--> ndim is the function used to determine the dimension of array

  



In [7]:
# two dimension array
import numpy as np
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print("two dimension array is: \n",arr2)
print(arr2.ndim)
# three dimension array
arr3 = np.array([[[1,2,3,4],[5,6,7,8],[7,8,9,10]]])
print("three dimension array is : \n",arr3)
print(arr3.ndim)

# 10-D array
arr10 = np.array([1,2,3,4],ndmin=10)
print("10-D array: \n",arr10)
print(arr10.ndim)

two dimension array is: 
 [[1 2 3 4]
 [1 2 3 4]]
2
three dimension array is : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 7  8  9 10]]]
3
10-D array: 
 [[[[[[[[[[1 2 3 4]]]]]]]]]]
10
